### ISSUE TITLE
Filter Elders

### ISSUE THREAD

**Issue by swhalley** [peidevs/Scooter-User-Generator#1]
https://api.meetup.com/2/profiles?key={key}&sign=true&role=leads&group_urlname=pei-developers

This call will get us the leaders of the group.
see "role=leads"

**Comment by 2manyprojects2littletime** [comment]
The API key is a session key or an application key? I guess what I mean is do I have to get a new key every meetup or just go through the steps in the readme once?

**Comment by swhalley** [comment]
You will only ever have one key, so you should only have to go through the steps in the readme once. Your key is assigned to your meetup profile.

didn't want to put my key in source control :p

**Comment by 2manyprojects2littletime** [comment]
ok, sounds good.  I’m just lookey-looing, and I guess that’s not really specific to the issue/enh anyway so sorry for the distraction.

**Comment by swhalley** [comment]
committed changes last night for this
